/*
Currently, macOS backend is mostly generated by Gemini 3 Pro.
I do not wish to touch Objective-C as much as the next person.
If someone more experienced in Obj-C/Swift wants to refactor this,
please do so.
*/
#import <Foundation/Foundation.h>
#import <IOBluetooth/IOBluetooth.h>
#include <deque>
#include <vector>
#include <mutex>
#include <string>

#include "../Platform.hpp"
#include <mdr-c/Platform/PlatformMacOS.h>

@interface MDRBluetoothDelegate : NSObject <IOBluetoothRFCOMMChannelDelegate>
@property (nonatomic, strong) IOBluetoothRFCOMMChannel *rfcommChannel;
@property (nonatomic, strong) NSMutableData *buffer;
@property (nonatomic, assign) BOOL isConnected;
@property (nonatomic, assign) BOOL isConnecting;
@property (nonatomic, assign) BOOL isQueryingSDP;
@property (nonatomic, strong) NSString *lastError;
@property (nonatomic, strong) NSString *targetUUID;
@property (nonatomic, strong) NSString *targetAddress;

- (void)appendData:(NSData *)data;
- (NSData *)readData:(NSUInteger)maxLength;
- (void)connectToAddress:(NSString *)address serviceUUID:(NSString *)uuid;
- (void)disconnect;
- (void)sendData:(NSData *)data;
- (void)sdpQueryComplete:(IOBluetoothDevice *)device status:(IOReturn)status;
@end

@implementation MDRBluetoothDelegate
{
    std::mutex _bufferMutex;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _buffer = [NSMutableData data];
        _isConnected = NO;
        _isConnecting = NO;
        _isQueryingSDP = NO;
        _lastError = @"";
    }
    return self;
}

- (void)appendData:(NSData *)data {
    std::lock_guard<std::mutex> lock(_bufferMutex);
    [_buffer appendData:data];
}

- (NSData *)readData:(NSUInteger)maxLength {
    std::lock_guard<std::mutex> lock(_bufferMutex);
    if (_buffer.length == 0) {
        return nil;
    }
    
    NSUInteger len = MIN(maxLength, _buffer.length);
    NSData *subData = [_buffer subdataWithRange:NSMakeRange(0, len)];
    [_buffer replaceBytesInRange:NSMakeRange(0, len) withBytes:NULL length:0];
    return subData;
}

- (void)connectToAddress:(NSString *)address serviceUUID:(NSString *)uuidString {
    NSLog(@"[MDR] Connecting to %@ with UUID %@", address, uuidString);
    self.isConnecting = YES;
    self.isQueryingSDP = YES;
    self.lastError = @"";
    self.targetUUID = uuidString;
    self.targetAddress = address;
    self.isConnected = NO;
    
    IOBluetoothDevice *device = [IOBluetoothDevice deviceWithAddressString:address];
    if (!device) {
        self.lastError = @"Device not found";
        self.isConnecting = NO;
        self.isQueryingSDP = NO;
        return;
    }
    
    IOReturn sdpResult = [device performSDPQuery:self];
    if (sdpResult != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"SDP start failed: 0x%x", sdpResult];
        self.isConnecting = NO;
        self.isQueryingSDP = NO;
        return;
    }
}

- (void)sdpQueryComplete:(IOBluetoothDevice *)device status:(IOReturn)status {
    NSLog(@"[MDR] SDP query complete for %@ with status 0x%x", device.addressString, status);
    self.isQueryingSDP = NO;
    
    if (!self.isConnecting) return;
    
    if (status != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"SDP query failed: 0x%x", status];
        self.isConnecting = NO;
        return;
    }
    
    uint8_t uuidBytes[16];
    if (serviceUUIDtoBytes([self.targetUUID UTF8String], uuidBytes) != 0) {
        self.lastError = @"Invalid UUID string";
        self.isConnecting = NO;
        return;
    }

    IOBluetoothSDPUUID *uuid = [IOBluetoothSDPUUID uuidWithBytes:uuidBytes length:16];
    IOBluetoothSDPServiceRecord *serviceRecord = [device getServiceRecordForUUID:uuid];
    
    if (!serviceRecord) {
        NSLog(@"[MDR] Service record NOT found for UUID %@", self.targetUUID);
        self.lastError = @"MDR Service record not found";
        self.isConnecting = NO;
        return;
    }
    
    BluetoothRFCOMMChannelID channelID;
    if ([serviceRecord getRFCOMMChannelID:&channelID] != kIOReturnSuccess) {
        self.lastError = @"Could not get RFCOMM Channel ID";
        self.isConnecting = NO;
        return;
    }
    
    NSLog(@"[MDR] Opening RFCOMM channel %d", (int)channelID);
    
    IOBluetoothRFCOMMChannel *channel = nil;
    IOReturn result = [device openRFCOMMChannelAsync:&channel withChannelID:channelID delegate:self];
    
    if (result != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"RFCOMM open failed: 0x%x", result];
        self.isConnecting = NO;
        return;
    }
    
    self.rfcommChannel = channel;
}

- (void)disconnect {
    if (self.rfcommChannel) {
        [self.rfcommChannel closeChannel];
        self.rfcommChannel = nil;
    }
    self.isConnected = NO;
    self.isConnecting = NO;
    self.isQueryingSDP = NO;
}

- (void)sendData:(NSData *)data {
    if (self.rfcommChannel && self.isConnected) {
        IOReturn res = [self.rfcommChannel writeAsync:(void *)data.bytes length:data.length refcon:NULL];
        if (res != kIOReturnSuccess) {
            NSLog(@"[MDR] Write failed: 0x%x", res);
        }
    }
}

// IOBluetoothRFCOMMChannelDelegate methods

- (void)rfcommChannelOpenComplete:(IOBluetoothRFCOMMChannel *)rfcommChannel status:(IOReturn)error {
    NSLog(@"[MDR] RFCOMM open complete with status 0x%x", error);
    if (error != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"RFCOMM open failed: 0x%x", error];
        self.isConnecting = NO;
        self.isConnected = NO;
        self.rfcommChannel = nil;
        return;
    }
    self.isConnected = YES;
    self.isConnecting = NO;
}

- (void)rfcommChannelData:(IOBluetoothRFCOMMChannel *)rfcommChannel data:(void *)dataPointer length:(size_t)dataLength {
    NSData *data = [NSData dataWithBytes:dataPointer length:dataLength];
    [self appendData:data];
}

- (void)rfcommChannelClosed:(IOBluetoothRFCOMMChannel *)rfcommChannel {
    NSLog(@"[MDR] RFCOMM channel closed");
    self.isConnected = NO;
    self.isConnecting = NO;
    self.rfcommChannel = nil;
}

@end

struct MDRConnectionMacOS
{
    MDRConnection mdrConn;
    MDRBluetoothDelegate *delegate;
    
    MDRConnectionMacOS() {
        delegate = [[MDRBluetoothDelegate alloc] init];
        mdrConn = {
            .user = this,
            .connect = Connect,
            .disconnect = Disconnect,
            .recv = Recv,
            .send = Send,
            .poll = Poll,
            .getDevicesList = GetDevicesList,
            .freeDevicesList = FreeDevicesList,
            .getLastError = GetLastError
        };
    }
    
    ~MDRConnectionMacOS() {
        [delegate disconnect];
        delegate = nil;
    }

    static int Connect(void* user, const char* macAddress, const char* serviceUUID) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            NSString *addrParams = [NSString stringWithUTF8String:macAddress];
            NSString *uuidParams = [NSString stringWithUTF8String:serviceUUID];
            [self->delegate connectToAddress:addrParams serviceUUID:uuidParams];
            if (self->delegate.lastError && self->delegate.lastError.length > 0 && !self->delegate.isConnecting && !self->delegate.isQueryingSDP) {
                return MDR_RESULT_ERROR_NET;
            }
            return MDR_RESULT_INPROGRESS;
        }
    }

    static void Disconnect(void* user) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            [self->delegate disconnect];
        }
    }

    static int Recv(void* user, char* dst, int size, int* pReceived) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            if (!self->delegate.isConnected) {
                return MDR_RESULT_ERROR_NO_CONNECTION;
            }
            NSData *data = [self->delegate readData:size];
            if (data && data.length > 0) {
                memcpy(dst, data.bytes, data.length);
                *pReceived = (int)data.length;
                return MDR_RESULT_OK;
            }
            return MDR_RESULT_INPROGRESS; 
        }
    }

    static int Send(void* user, const char* src, int size, int* pSent) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            if (!self->delegate.isConnected) {
                return MDR_RESULT_ERROR_NO_CONNECTION;
            }
            NSData *data = [NSData dataWithBytes:src length:size];
            [self->delegate sendData:data];
            *pSent = size;
            return MDR_RESULT_OK;
        }
    }

    static int Poll(void* user, int timeout) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            if (timeout < 0) timeout = 1000;
            double seconds = timeout / 1000.0;
            if (seconds <= 0) seconds = 0.0001; 
            NSDate *limitDate = [NSDate dateWithTimeIntervalSinceNow:seconds];
            [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:limitDate];
            if (self->delegate.lastError && self->delegate.lastError.length > 0 && !self->delegate.isConnected && !self->delegate.isConnecting && !self->delegate.isQueryingSDP) {
                return MDR_RESULT_ERROR_NET;
            }
            if (self->delegate.isConnected) {
                return MDR_RESULT_OK;
            }
            if (self->delegate.isConnecting || self->delegate.isQueryingSDP) {
                return MDR_RESULT_INPROGRESS; 
            }
            return MDR_RESULT_ERROR_NET;
        }
    }

    static int GetDevicesList(void* user, MDRDeviceInfo** ppList, int* pCount) {
        @autoreleasepool {
            NSArray *allDevices = [IOBluetoothDevice pairedDevices];
            if (!allDevices || allDevices.count == 0) {
                *pCount = 0;
                *ppList = nullptr;
                return MDR_RESULT_OK;
            }
            NSMutableArray *filteredDevices = [NSMutableArray array];
            for (IOBluetoothDevice *dev in allDevices) {
                NSString *name = dev.name;
                if (!name) continue;
                BOOL isSony = [name rangeOfString:@"Sony" options:NSCaseInsensitiveSearch].location != NSNotFound ||
                              [name rangeOfString:@"LinkBuds" options:NSCaseInsensitiveSearch].location != NSNotFound ||
                              [name hasPrefix:@"WH-"] ||
                              [name hasPrefix:@"WF-"] ||
                              [name hasPrefix:@"MDR-"] ||
                              [name hasPrefix:@"WI-"] ||
                              [name rangeOfString:@"SONY" options:0].location != NSNotFound;
                if (isSony) {
                    [filteredDevices addObject:dev];
                }
            }
            if (filteredDevices.count == 0) {
                *pCount = 0;
                *ppList = nullptr;
                return MDR_RESULT_OK;
            }
            *ppList = new MDRDeviceInfo[filteredDevices.count];
            *pCount = (int)filteredDevices.count;
            for (NSUInteger i = 0; i < filteredDevices.count; i++) {
                IOBluetoothDevice *dev = filteredDevices[i];
                NSString *name = dev.name;
                NSString *addr = [dev.addressString stringByReplacingOccurrencesOfString:@"-" withString:@":"];
                MDRDeviceInfo *info = &(*ppList)[i];
                memset(info, 0, sizeof(MDRDeviceInfo));
                if (name) {
                    strncpy(info->szDeviceName, [name UTF8String], sizeof(info->szDeviceName) - 1);
                }
                if (addr) {
                    strncpy(info->szDeviceMacAddress, [addr UTF8String], sizeof(info->szDeviceMacAddress) - 1);
                }
            }
            return MDR_RESULT_OK;
        }
    }
    
    static int FreeDevicesList(void* user, MDRDeviceInfo** ppList) {
        if (*ppList)
        {
            delete[] *ppList;
            *ppList = nullptr;
        }
        return MDR_RESULT_OK;
    }
    
    static const char* GetLastError(void* user) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        if (self->delegate.lastError && self->delegate.lastError.length > 0) {
             return [self->delegate.lastError UTF8String];
        }
        return "";
    }
};

MDRConnectionMacOS* mdrConnectionMacOSCreate() { return new MDRConnectionMacOS(); }
MDRConnection* mdrConnectionMacOSGet(MDRConnectionMacOS* self) { return &self->mdrConn; }
void mdrConnectionMacOSDestroy(MDRConnectionMacOS* self) { delete self; }
